### ISSUE TITLE
User-specified probabilities of ratings in the case of disagreement in simulated rating matrix

### ISSUE THREAD

**Issue by stevekambouris** [jbryer/IRRsim#2]
https://github.com/jbryer/IRRsim/blob/5c8b1583d91d853ea438340b4b0c471f0980f9a5/R/simulateRatingMatrix.R#L47-L50

For the case of disagreement, should the ratings be sampled from 1:nLevels, which will be specified in the same order as response.probs, rather than l, which is a random permutation of 1:nLevels? Unless I've missed something, this sample() will apply the probabilities in response.probs to a random ordering of the 1:nLevels ratings, rather than the user-intended ordering.

**Comment by jbryer** [comment]
Thanks for this issue. This has been fixed on Github.
