### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by schyler-rad** [jbryer/IRRsim#3]
I had a lot of issues installing the package. I got an error like:

`Error: (converted from warning) package 'DescTools' was built under R version 4.0.2`

 and there was an error that had something to do with the `backports` package.

**Comment by jbryer** [comment]
Try installing the DescTools package
separately: install.packages('DescTools')
I suspect there is a version mismatch. Are you running R 4.0.2?

**Comment by schyler-rad** [comment]
I updated to 4.0.2, thinking that would be a silly of me to have ignored that solution.

That made the error with `DescTools` go away, but then `backports` was acting up.

I had to remove the file from my "C" drive, download backports separately again, and then the github download worked.
