### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by fred-oswald** [jbryer/IRRsim#4]
IRRsim installs locally with
devtools::install_github('jbryer/IRRsim')

but then running

IRRsim_demo(clean = FALSE)

produces the following error

Error in IRRsim_demo(clean = FALSE) : 
  could not find function "IRRsim_demo"

thanks for your support!

**Comment by jbryer** [comment]
Can you give it a try again. I was unable to reproduce the error but recreated the documentation and verified that IRRsim_demo is exported in the NAMESPACE file.

**Comment by fred-oswald** [comment]
it works now - thank you, Jason!

Best,
Fred

Fred Oswald
workforce.rice.edu | @FredOswald <https://twitter.com/FredOswald> | calendar
<http://workforce.rice.edu/contact/>
